### ISSUE TITLE
Testing a specific command failed

### ISSUE THREAD

**Issue by XIYU11864** [prysk/prysk#222]
# Summary

clean-css-cli is a command-line interface to [clean-css](https://github.com/jakubpawlowicz/clean-css) - fast and efficient CSS optimizer for [Node.js](http://nodejs.org/).

prysk can't run the test: 
```
  $ cleancss -h
```
## Reproducing the Issue

Reproducibility:  always

### Steps to reproduce the behavior:
1. create a new `test.t` file
2. write this line into the file:
```
  $ cleancss -h
```
3. run `prysk test.t`
4. report an error:
```
Traceback (most recent call last):
  File "/home/xiyu/.local/bin/prysk", line 8, in <module>
    sys.exit(main())
  File "/home/xiyu/.local/lib/python3.9/site-packages/prysk/__init__.py", line 9, in main
    sys.exit(prysk.cli.main())
  File "/home/xiyu/.local/lib/python3.9/site-packages/prysk/cli.py", line 47, in main
    return _Cli().main(argv)
  File "/home/xiyu/.local/lib/python3.9/site-packages/prysk/cli.py", line 537, in main
    _, _, diff = test()
  File "/home/xiyu/.local/lib/python3.9/site-packages/prysk/cli.py", line 317, in testwrapper
    refout, postout, diff = test()
  File "/home/xiyu/.local/lib/python3.9/site-packages/prysk/test.py", line 370, in test
    return testfile(
  File "/home/xiyu/.local/lib/python3.9/site-packages/prysk/test.py", line 321, in testfile
    return test(
  File "/home/xiyu/.local/lib/python3.9/site-packages/prysk/test.py", line 238, in test
    ret = int(cmd.split()[1])
ValueError: invalid literal for int() with base 10: b'$?'
```

## Expected Behaviour

if run anothor app's `-h` command, should print something like this:
```
!
--- muti_line.t
+++ muti_line.t.err
@@ -1,1 +1,29 @@
   $ prysk -h
+  usage: prysk [OPTIONS] TESTS...
+  
+  positional arguments:
+    TESTS                 Path(s) to the tests to be executed
+  
+  optional arguments:
+    -h, --help            show this help message and exit
+    -V, --version         show program's version number and exit
+    -q, --quiet           don't print diffs (default: False)
+    -v, --verbose         show filenames and test status (default: False)
+    -i, --interactive     interactively merge changed test output (default:
+                          False)
+    -d, --debug           write script output directly to the terminal (default:
+                          False)
+    -y, --yes             answer yes to all questions (default: False)
+    -n, --no              answer no to all questions (default: False)
+    -E, --preserve-env    don't reset common environment variables (default:
+                          False)
+    --keep-tmpdir         keep temporary directories (default: False)
+    --shell PATH          shell to use for running tests (default: /bin/sh)
+    --shell-opts OPTS     arguments to invoke shell with (default: None)
+    --indent NUM          number of spaces to use for indentation (default: 2)
+    --color {always,never,auto}
+                          Mode which shall be used for coloring the output
+                          (default: auto)
+    --xunit-file PATH     path to write xUnit XML output (default: None)
+    --dos2unix            convert DOS/Windows line endings to UNIX line endings
+                          (default: False)

# Ran 1 tests, 0 skipped, 1 failed.
```

## Actual Behaviour

report an error.

## Root Cause

check the file `prysk/test.py` line 238, we see 
```python
ret = int(cmd.split()[1])
```
actully when constructing stdin list, whenever a line is encountered that begins with a command line prefix `($)` or a continuation line prefix `(>)`, a new line is added to the stdin list. This new line contains the usalt, the index of the current line, and a query for the exit status. command`($?)`.

maybe the index of the current line was missed in some case.

## Context

if run the `cleancss -h` directly, we get 
```
Usage: cleancss [options] <source-file ...>

Options:
  -b, --batch                    If enabled, optimizes input files one by one instead of joining them together
  -c, --compatibility [ie7|ie8]  Force compatibility mode (see Readme for advanced examples)
  -d, --debug                    Shows debug information (minification time & compression efficiency)
  -f, --format <options>         Controls output formatting, see examples below
  -h, --help                     display this help
  -o, --output [output-file]     Use [output-file] as output instead of STDOUT
  -O <n> [optimizations]         Turn on level <n> optimizations; optionally accepts a list of fine-grained options, defaults to `1`, see
                                 examples below, IMPORTANT: the prefix is O (a capital o letter), NOT a 0 (zero, a number)
  -v, --version                  output the version number
  --batch-suffix <suffix>        A suffix (without extension) appended to input file name when processing in batch mode (`-min` is the
                                 default) (default: "-min")
  --inline [rules]               Enables inlining for listed sources (defaults to `local`)
  --inline-timeout [seconds]     Per connection timeout when fetching remote stylesheets (defaults to 5 seconds)
  --input-source-map [file]      Specifies the path of the input source map file
  --remove-inlined-files         Remove files inlined in <source-file ...> or via `@import` statements
  --source-map                   Enables building input's source map
  --source-map-inline-sources    Enables inlining sources inside source maps
  --with-rebase                  Enable URLs rebasing
  --watch                        Runs CLI in watch mode

Examples:

  %> cleancss one.css
  %> cleancss -o one-min.css one.css
  %> cleancss -o merged-and-minified.css one.css two.css three.css
  %> cleancss one.css two.css three.css | gzip -9 -c > merged-minified-and-gzipped.css.gz

Formatting options:
  %> cleancss --format beautify one.css
  %> cleancss --format keep-breaks one.css
  %> cleancss --format 'indentBy:1;indentWith:tab' one.css
  %> cleancss --format 'breaks:afterBlockBegins=on;spaces:aroundSelectorRelation=on' one.css
  %> cleancss --format 'breaks:afterBlockBegins=2;spaces:aroundSelectorRelation=on' one.css

Level 0 optimizations:
  %> cleancss -O0 one.css

Level 1 optimizations:
  %> cleancss -O1 one.css
  %> cleancss -O1 removeQuotes:off;roundingPrecision:4;specialComments:1 one.css
  %> cleancss -O1 all:off;specialComments:1 one.css

Level 2 optimizations:
  %> cleancss -O2 one.css
  %> cleancss -O2 mergeMedia:off;restructureRules:off;mergeSemantically:on;mergeIntoShorthands:off one.css
  %> cleancss -O2 all:off;removeDuplicateRules:on one.css
```
maybe some content of this output cannot be read by prysk. cram also can not read by the way.

### System
**Desktop:**
 - OS: wsl2 (openEuler 22.03)
 - Python Version: Python  3.9.9
 - Package Version: 0.16.0

**Comment by Nicoretti** [comment]
Hi @XIYU11864,

Thank you for reporting the issue :+1: .

Did you experience this problem with `prysk versions <= 0.15.0` too?

**Heads up:**
I personally do not have a Windows machine and see Windows-related issues as critical as the Unix ones because we do not officially support it yet. That said, if you can upload the output which caused the issue `cleancss -h > output.txt`, I might be able to reproduce the issue via a general test case.

Best,  
Nico

**Comment by XIYU11864** [comment]
I have not used version 0.15.0. And I just tried the 0.15.0 version, but the result did not change.
<img width="635" alt="2023-12-17 222356" src="https://github.com/prysk/prysk/assets/75518225/07f7d6d6-8d4d-43c5-b37c-8d7fa252e0e0">

This is the `cleancss -h` output.
[output.txt](https://github.com/prysk/prysk/files/13696447/output.txt)

**Comment by Nicoretti** [comment]
@XIYU11864 which version of  `cleancss` did you use?

**Comment by XIYU11864** [comment]
> @XIYU11864 which version of `cleancss` did you use?

5.6.3

**Comment by Nicoretti** [comment]
@XIYU11864 was the `cleancss` installed in the windows or in `wsl` context?

**Comment by XIYU11864** [comment]
> @XIYU11864 was the `cleancss` installed in the windows or in `wsl` context?

In wsl actually. The `wsl` is same as a linux environment I guess?

**Comment by Nicoretti** [comment]
> > @XIYU11864 was the `cleancss` installed in the windows or in `wsl` context?
> 
> In wsl actually. The `wsl` is same as a linux environment I guess?

I would assume so, but my knowledge of the Windows `WSL` environment is limited. I'm currently experimenting with `cleancss 5.6.2`. Sadly, I can't reproduce the problem yet. On the other hand, I've found odd behavior when interacting with other processes.

For example, in Vim, executing `r! cleancss -h` doesn't really work...

Line endings in `output.txt `are `Unix` (LF), so that's one less suspicion/hunch.

**Comment by Nicoretti** [comment]
@XIYU11864 could you run `prysk` in debug mode and provide the outputs?
```
prysk --debug --keep-tempdir yourtestifle.t
```

**Comment by XIYU11864** [comment]
> @XIYU11864 could you run `prysk` in debug mode and provide the outputs?
> 
> ```
> prysk --debug --keep-tempdir yourtestifle.t
> ```

sorry but...
<img width="391" alt="2023-12-17 235747" src="https://github.com/prysk/prysk/assets/75518225/fdcf58b2-488a-4145-a9cd-35c8e22fa41d">
only 2 directories, no files in the directory.
Now I think maybe there are some problems with my python version. Let me try using other versions of python.

**Comment by Nicoretti** [comment]
@XIYU11864, I have created a regression test using the output from the `cleancss -h` command (#223). Please run this test in the WSL environment. It appears to work correctly there. If it also functions as expected in WSL, then the issue might lie with the `command` or its `invocation`. Processing its output should be validated by the test I've added.

**Comment by Nicoretti** [comment]
@mehulkar, @nigels-com  any idea or hunch on this windows/wsl issue?

**Comment by XIYU11864** [comment]
> @XIYU11864, I have created a regression test using the output from the `cleancss -h` command (#223). Please run this test in the WSL environment. It appears to work correctly there. If it also functions as expected in WSL, then the issue might lie with the `command` or its `invocation`. Processing its output should be validated by the test I've added.

Yes. I found that the `clean-css-cli` uses a strange way to output `-h` information. See https://github.com/clean-css/clean-css-cli/blob/master/index.js#L23 
So I maybe this issue is not a problem with prysk. Sorry for wasting everyone's time.

**Comment by Nicoretti** [comment]
Hi @XIYU11864 ,

My knowledge in `JS` and `Node` is quite limited. However, based on what I've found in the [Node.js documentation](https://nodejs.org/docs/latest/api/console.html#consolelogdata-args), `console.log` generally writes to `stdout`. There can be various issues with pipelining or interactions with other processes, such as unexpected behavior in buffer flushing. I've encountered similar issues in `Python`, where using `python -u` (forcing `stdout` and `stderr` streams to be unbuffered) has resolved the problem. Nevertheless, my understanding of `JS` and `Node` is too limited to be certain.

> ...
> So I maybe this issue is not a problem with prysk. Sorry for wasting everyone's time.

It's okay, these discussions are part of the process, and we're here to help as much as we can.

## How to continue?
Currently, my main challenge is reproducing the issue. Setting up a Windows system for this isn't something I'm keen on doing, and our `Windows CI` is still a [work in progress](https://github.com/prysk/prysk/pull/208).

At this moment, the best I can offer is to investigate further if you can provide a regression that fails in our current CI or that I can reproduce on a Linux machine.

There's a chance that @mehulkar or @nigels-com  might have some insights, as they also use prysk on Windows. However, since they haven't reported back, they might not have any immediate solutions.

Although I can't offer a direct solution to your problem, I hope this clarifies the situation well enough for you to make an informed decision.

Best
Nico

**Comment by XIYU11864** [comment]
@Nicoretti 
If you mean let me run the https://github.com/prysk/prysk/pull/223 test, It works. This is the results:

```
~/coding/test 
❯ cat test.t
# echo was chosen because escaping conflicting symbols like `1` or `@import` wasn't straight forward with heredoc
  $ echo "Usage: cleancss [options] <source-file ...>" >> cleancss-output.txt
  $ echo "Options:" >> cleancss-output.txt
  $ echo "  -b, --batch                    If enabled, optimizes input files one by one" >> cleancss-output.txt
  $ echo "                                 instead of joining them together" >> cleancss-output.txt
  $ echo "  -c, --compatibility [ie7|ie8]  Force compatibility mode (see Readme for" >> cleancss-output.txt
  $ echo "                                 advanced examples)" >> cleancss-output.txt
  $ echo "  -d, --debug                    Shows debug information (minification time &" >> cleancss-output.txt
  $ echo "                                 compression efficiency)" >> cleancss-output.txt
  $ echo "  -f, --format <options>         Controls output formatting, see examples below" >> cleancss-output.txt
  $ echo "  -h, --help                     display this help" >> cleancss-output.txt
  $ echo "  -o, --output [output-file]     Use [output-file] as output instead of STDOUT" >> cleancss-output.txt
  $ echo "  -O <n> [optimizations]         Turn on level <n> optimizations; optionally" >> cleancss-output.txt
  $ echo "                                 accepts a list of fine-grained options," >> cleancss-output.txt
  $ echo "                                 defaults to \`1\`, see examples below," >> cleancss-output.txt
  $ echo "                                 IMPORTANT: the prefix is O (a capital o" >> cleancss-output.txt
  $ echo "                                 letter), NOT a 0 (zero, a number)" >> cleancss-output.txt
  $ echo "  -v, --version                  output the version number" >> cleancss-output.txt
  $ echo "  --batch-suffix <suffix>        A suffix (without extension) appended to input" >> cleancss-output.txt
  $ echo "                                 file name when processing in batch mode" >> cleancss-output.txt
  $ echo "                                 (\`-min\` is the default) (default: \"-min\")" >> cleancss-output.txt
  $ echo "  --inline [rules]               Enables inlining for listed sources (defaults" >> cleancss-output.txt
  $ echo "                                 to \`local\`)" >> cleancss-output.txt
  $ echo "  --inline-timeout [seconds]     Per connection timeout when fetching remote" >> cleancss-output.txt
  $ echo "                                 stylesheets (defaults to 5 seconds)" >> cleancss-output.txt
  $ echo "  --input-source-map [file]      Specifies the path of the input source map" >> cleancss-output.txt
  $ echo "                                 file" >> cleancss-output.txt
  $ echo "  --remove-inlined-files         Remove files inlined in <source-file ...> or" >> cleancss-output.txt
  $ echo "                                 via \`@import\` statements" >> cleancss-output.txt
  $ echo "  --source-map                   Enables building input's source map" >> cleancss-output.txt
  $ echo "  --source-map-inline-sources    Enables inlining sources inside source maps" >> cleancss-output.txt
  $ echo "  --with-rebase                  Enable URLs rebasing" >> cleancss-output.txt
  $ echo "  --watch                        Runs CLI in watch mode" >> cleancss-output.txt
  $ echo >> cleancss-output.txt
  $ echo "Examples:" >> cleancss-output.txt
  $ echo >> cleancss-output.txt
  $ echo "  %> cleancss one.css" >> cleancss-output.txt
  $ echo "  %> cleancss -o one-min.css one.css" >> cleancss-output.txt
  $ echo "  %> cleancss -o merged-and-minified.css one.css two.css three.css" >> cleancss-output.txt
  $ echo "  %> cleancss one.css two.css three.css | gzip -9 -c > merged-minified-and-gzipped.css.gz" >> cleancss-output.txt
  $ echo >> cleancss-output.txt
  $ echo "Formatting options:" >> cleancss-output.txt
  $ echo "  %> cleancss --format beautify one.css" >> cleancss-output.txt
  $ echo "  %> cleancss --format keep-breaks one.css" >> cleancss-output.txt
  $ echo "  %> cleancss --format 'indentBy:1;indentWith:tab' one.css" >> cleancss-output.txt
  $ echo "  %> cleancss --format 'breaks:afterBlockBegins=on;spaces:aroundSelectorRelation=on' one.css" >> cleancss-output.txt
  $ echo "  %> cleancss --format 'breaks:afterBlockBegins=2;spaces:aroundSelectorRelation=on' one.css" >> cleancss-output.txt
  $ echo >> cleancss-output.txt
  $ echo "Level 0 optimizations:" >> cleancss-output.txt
  $ echo "  %> cleancss -O0 one.css" >> cleancss-output.txt
  $ echo >> cleancss-output.txt
  $ echo "Level 1 optimizations:" >> cleancss-output.txt
  $ echo "  %> cleancss -O1 one.css" >> cleancss-output.txt
  $ echo "  %> cleancss -O1 removeQuotes:off;roundingPrecision:4;specialComments:1 one.css" >> cleancss-output.txt
  $ echo "  %> cleancss -O1 all:off;specialComments:1 one.css" >> cleancss-output.txt
  $ echo >> cleancss-output.txt
  $ echo "Level 2 optimizations:" >> cleancss-output.txt
  $ echo "  %> cleancss -O2 one.css" >> cleancss-output.txt
  $ echo "  %> cleancss -O2 mergeMedia:off;restructureRules:off;mergeSemantically:on;mergeIntoShorthands:off one.css" >> cleancss-output.txt
  $ echo "  %> cleancss -O2 all:off;removeDuplicateRules:on one.css" >> cleancss-output.txt

  $ cat > cleancss << EOF
  > #!/bin/sh
  > cat cleancss-output.txt
  > EOF

  $ chmod u+x cleancss

  $ export PATH=`pwd`:$PATH

  $ cleancss
  Usage: cleancss [options] <source-file ...>
  Options:
    -b, --batch                    If enabled, optimizes input files one by one
                                   instead of joining them together
    -c, --compatibility [ie7|ie8]  Force compatibility mode (see Readme for
                                   advanced examples)
    -d, --debug                    Shows debug information (minification time &
                                   compression efficiency)
    -f, --format <options>         Controls output formatting, see examples below
    -h, --help                     display this help
    -o, --output [output-file]     Use [output-file] as output instead of STDOUT
    -O <n> [optimizations]         Turn on level <n> optimizations; optionally
                                   accepts a list of fine-grained options,
                                   defaults to `1`, see examples below,
                                   IMPORTANT: the prefix is O (a capital o
                                   letter), NOT a 0 (zero, a number)
    -v, --version                  output the version number
    --batch-suffix <suffix>        A suffix (without extension) appended to input
                                   file name when processing in batch mode
                                   (`-min` is the default) (default: "-min")
    --inline [rules]               Enables inlining for listed sources (defaults
                                   to `local`)
    --inline-timeout [seconds]     Per connection timeout when fetching remote
                                   stylesheets (defaults to 5 seconds)
    --input-source-map [file]      Specifies the path of the input source map
                                   file
    --remove-inlined-files         Remove files inlined in <source-file ...> or
                                   via `@import` statements
    --source-map                   Enables building input's source map
    --source-map-inline-sources    Enables inlining sources inside source maps
    --with-rebase                  Enable URLs rebasing
    --watch                        Runs CLI in watch mode
  
  Examples:
  
    %> cleancss one.css
    %> cleancss -o one-min.css one.css
    %> cleancss -o merged-and-minified.css one.css two.css three.css
    %> cleancss one.css two.css three.css | gzip -9 -c > merged-minified-and-gzipped.css.gz
  
  Formatting options:
    %> cleancss --format beautify one.css
    %> cleancss --format keep-breaks one.css
    %> cleancss --format 'indentBy:1;indentWith:tab' one.css
    %> cleancss --format 'breaks:afterBlockBegins=on;spaces:aroundSelectorRelation=on' one.css
    %> cleancss --format 'breaks:afterBlockBegins=2;spaces:aroundSelectorRelation=on' one.css
  
  Level 0 optimizations:
    %> cleancss -O0 one.css
  
  Level 1 optimizations:
    %> cleancss -O1 one.css
    %> cleancss -O1 removeQuotes:off;roundingPrecision:4;specialComments:1 one.css
    %> cleancss -O1 all:off;specialComments:1 one.css
  
  Level 2 optimizations:
    %> cleancss -O2 one.css
    %> cleancss -O2 mergeMedia:off;restructureRules:off;mergeSemantically:on;mergeIntoShorthands:off one.css
    %> cleancss -O2 all:off;removeDuplicateRules:on one.css

~/coding/test 
❯ prysk test.t
.
# Ran 1 tests, 0 skipped, 0 failed.
```

**Comment by Nicoretti** [comment]
@XIYU11864 yes for me this regression passes to ... that's the problem 😅 .
I would need a regression which `fails`  (with the problem of yours on "linux"), so I can debug the issue.

**Comment by Nicoretti** [comment]
You might consider developing specific test cases to better understand the issue from the `cleancss` side. For example:

- Test Case involving Vim: 
    > When executing a command like `:r! cleancss -h` in Vim, it doesn't work as expected.

To further investigate this issue, you could:

1. **Clarify with the `cleancss` Author/Team**: Reach out to the developers of `cleancss` to understand if there are known issues or limitations when running their tool in a shell pipeline or as a subprocess.

2. **Consult with a JavaScript/Node.js Expert**: Seek advice from someone with in-depth knowledge of JavaScript and Node.js. They can offer insights into how Node.js applications behave in different shell environments and might suggest solutions or workarounds.

**Comment by Nicoretti** [comment]
@XIYU11864, I'm going to close this issue for now. If you have any feedback or additional details from the 'cleancss' tools side, please don't hesitate to reopen the issue at any time. I hope that course of action is ok with you.

best
Nico

**Comment by nigels-com** [comment]
I'm willing to take a look on Windows.  But I'm off work until Jan 3rd and wouldn't be inclined to boot up the Windows laptop until then.  I tend to use msys2 rather than wsl2, and our go-to node.js version is fairly old, so could turn into a bit of a journey, to be honest.  One thing that comes to mind is running that command in very minimal terminal mode such TERM=xterm or TERM=dumb, the environment that prysk uses isn't _exactly_ vanillia command-line, as I understand it.

**Comment by Nicoretti** [comment]
Any updates on this, or should we close it?
